version: "3"
services:
  server:
    container_name: server
    environment:
      - MONGO_URI=mongodb://restheart:R3ste4rt!@mongo:27017
    build:
      context: ./server
      target: base
    depends_on:
      - mongo
    restart: always
    volumes:
      - server-data:/home/app/server
      - nodemon-json:/home/app/server/nodemon.json
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: restheart
      MONGO_INITDB_ROOT_PASSWORD: R3ste4rt!
    command: --bind_ip_all --auth
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://restheart:R3ste4rt!@mongo:27017/

volumes:
  mongo-data:
  server-data:
  nodemon-json:
